# Generated by Django 3.2.18 on 2023-03-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=255)),
                ('short_code', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
